// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh759mnm-PqbsKOXLv-aDdVFqIdK50IEs',
    appId: '1:922168577978:web:2cefa3bbe46e6a8dd09783',
    messagingSenderId: '922168577978',
    projectId: 'belajarfirebase-4e1a3',
    authDomain: 'belajarfirebase-4e1a3.firebaseapp.com',
    storageBucket: 'belajarfirebase-4e1a3.firebasestorage.app',
    measurementId: 'G-8CYK5089LT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ3nKkljynq42GhhE_P3PWga8Fzm9Vf7A',
    appId: '1:922168577978:android:9786c772277cc0ecd09783',
    messagingSenderId: '922168577978',
    projectId: 'belajarfirebase-4e1a3',
    storageBucket: 'belajarfirebase-4e1a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwAip2ECefRQfYryvvasd-w5yMm4FHZgc',
    appId: '1:922168577978:ios:b243ec0c25cf3877d09783',
    messagingSenderId: '922168577978',
    projectId: 'belajarfirebase-4e1a3',
    storageBucket: 'belajarfirebase-4e1a3.firebasestorage.app',
    iosBundleId: 'com.example.belajar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwAip2ECefRQfYryvvasd-w5yMm4FHZgc',
    appId: '1:922168577978:ios:b243ec0c25cf3877d09783',
    messagingSenderId: '922168577978',
    projectId: 'belajarfirebase-4e1a3',
    storageBucket: 'belajarfirebase-4e1a3.firebasestorage.app',
    iosBundleId: 'com.example.belajar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh759mnm-PqbsKOXLv-aDdVFqIdK50IEs',
    appId: '1:922168577978:web:a9c8357025e8857cd09783',
    messagingSenderId: '922168577978',
    projectId: 'belajarfirebase-4e1a3',
    authDomain: 'belajarfirebase-4e1a3.firebaseapp.com',
    storageBucket: 'belajarfirebase-4e1a3.firebasestorage.app',
    measurementId: 'G-RYCHJRPS9K',
  );
}
